---
#  install and configure tmux and friends
 - name: install tmux
   dnf: name=tmux state=present
 - name: install tmuxinator
   dnf: name=tmuxinator state=present
 - name: configure tmux
   template: src=tmux.conf.j2 dest=/home/{{ user }}/.tmux.conf owner={{ user }} group={{ user }} mode=0600
