---
# c development packages, aka build-essential
- name: install c development packages
  dnf: name={{ item }} state=present
  with_items:
      - make
      - automake
      - gcc
      - gcc-c++
      - kernel-devel
